### PR TITLE
Handle errors gracefully when parsing GitHub version tags

### LINKED ISSUE #98: Execution error (ClassCastException) at antq.ver.github-tag/nth-newer?: class java.lang.String cannot be cast to class java.lang.Number
This input is causing it to fail:

```clj
(antq.ver/latest?
 {:type :github-tag,
  :file ".github/workflows/percy-issue-comment.yml",
  :name "octokit/request-action",
  :version "v2.x",
  :latest-version "v2.1.0",
  :repositories nil,
  :project :github-action,
  :diff-url nil,
  :latest-name nil,
  :only-newest-version? nil})
```

```
1. Caused by java.lang.ClassCastException
   class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in
   module java.base of loader 'bootstrap')

              Numbers.java:  263  clojure.lang.Numbers/gte
            github_tag.clj:   78  antq.ver.github-tag/nth-newer?
            github_tag.clj:   70  antq.ver.github-tag/nth-newer?
            github_tag.clj:   89  antq.ver.github-tag/eval14774/fn
              MultiFn.java:  229  clojure.lang.MultiFn/invoke
                      REPL:   21  antq.ver.github-tag/eval14947
                      REPL:   21  antq.ver.github-tag/eval14947
             Compiler.java: 7181  clojure.lang.Compiler/eval
             Compiler.java: 7136  clojure.lang.Compiler/eval
                  core.clj: 3202  clojure.core/eval
                  core.clj: 3198  clojure.core/eval
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  667  clojure.core/apply
                  core.clj: 1977  clojure.core/with-bindings*
                  core.clj: 1977  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn
                  main.clj:  437  clojure.main/repl/read-eval-print/fn
                  main.clj:  437  clojure.main/repl/read-eval-print
                  main.clj:  458  clojure.main/repl/fn
                  main.clj:  458  clojure.main/repl
                  main.clj:  368  clojure.main/repl
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  667  clojure.core/apply
                  core.clj:  662  clojure.core/apply
                regrow.clj:   20  refactor-nrepl.ns.slam.hound.regrow/wrap-clojure-repl/fn
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   84  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   56  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  152  nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                  AFn.java:   22  clojure.lang.AFn/run
               session.clj:  202  nrepl.middleware.session/session-exec/main-loop/fn
               session.clj:  201  nrepl.middleware.session/session-exec/main-loop
                  AFn.java:   22  clojure.lang.AFn/run
               Thread.java:  831  java.lang.Thread/run
```

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #98 (partially at least).

This change will log an error message if it's unable to parse GitHub version tags, then move on:

```
Error determining latest version for GitHub dep "octokit/request-action" (current: "v2.x", latest: "v2.1.0"): class java.lang.String cannot be cast to class java.lang.Number
```

This prevents the entire process from failing.

I don't know enough about the codebase to know what the expected behavior should actually be here, so please let me know if some other approach would be better. This is definitely an improvement over failing entirely tho IMO

### CODE REVIEW

File: src/antq/ver/github_tag.clj [hunk 1]
```diff
@@ -78,9 +78,17 @@
...
+          1 (nth-newer? current latest 0)
+          2 (and (nth-newer? current latest 0)
+                 (nth-newer? current latest 1))
+          (<= 0 (version/version-seq-compare current latest))))
+      (catch Throwable e
+        (log/error (format "Error determining latest version for GitHub dep %s (current: %s, latest: %s): %s"
+                           (pr-str (:name dep))
+                           (pr-str (:version dep))
+                           (pr-str (:latest-version dep))
+                           (ex-message e)))
```
Comment (liquidz) [inline src/antq/ver/github_tag.clj:93]: `ex-message` is available from Clojure 1.10.
Please use `.getMessage` for backward compatibility. (antq supports Clojure 1.8 or later)
```suggestion
                           (.getMessage e)))
```

**Review by liquidz — CHANGES_REQUESTED** [review]
@camsaul Thanks!
Overall this PR looks good.

Could you fix just one point for backward compatibility?

**Review by liquidz — APPROVED** [review]
Thanks!

**Comment by liquidz** [comment]
@camsaul I'll cut a new release later
